### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam'

### ISSUE THREAD

**Issue by chenHuiRu8** [zengxiaofei/HapHiC#12]
haphic pipeline --help
Traceback (most recent call last):
  File "/share/home/stu_chenhuiru/software/HapHiC-main/scripts/HapHiC_pipeline.py", line 17, in <module>
    import HapHiC_cluster
  File "/share/home/stu_chenhuiru/software/HapHiC-main/scripts/HapHiC_cluster.py", line 15, in <module>
    import pysam
ModuleNotFoundError: No module named 'pysam'
Traceback (most recent call last):
  File "/share/home/stu_chenhuiru/software/HapHiC-main/haphic", line 96, in <module>
    subprocess.run(commands, check=True)
  File "/share/home/stu_chenhuiru/miniconda3/lib/python3.11/subprocess.py", line 569, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/share/home/stu_chenhuiru/software/HapHiC-main/scripts/HapHiC_pipeline.py', '--help']' returned non-zero exit status 1.

**Comment by zengxiaofei** [comment]
Hi @chenHuiRu8,

This message means that the Python library `pysam` is not correctly installed.
Please install and activate the conda environment by following the tutorial:

```bash
# (2) Resolve dependencies
# We strongly recommend using conda to install dependencies. If you prefer manual installation, refer to HapHiC/conda_env/create_conda_env_py310.sh
$ conda env create -f HapHiC/conda_env/environment_py310.yml
# Activate the HapHiC conda environment
$ conda activate haphic # or: source /path/to/conda/bin/activate haphic
```
