### ISSUE TITLE
Failed to use haphic.

### ISSUE THREAD

**Issue by ZJin2021** [zengxiaofei/HapHiC#27]
Hi. I used the following command to mount my genome 'haphic pipeline asm_ctgs_m.fa HiC.filtered.bam 123 --correct_nrounds 2 --remove_allelic_links 3 --threads 40 --processes 40'. The program encountered a problem after the clusters step, and it seems like the grouping failed. However, I am also unable to use ALLHIC to group the sequences. This genome is considered to be an AAB type of triploid, and I have already used 3d-dna and yahs to mount it, managing to separate out 123 chromosomes. I have tried three types of assembly modes: hifiasm hap1+hap2, hicanu, and peregrine, but none of these assemblies could successfully run haphic. Could you provide some advice, thank you.

``peregrine + yahs``

``hifiasm hap merge + yahs``

``haphic log``
```
2024-05-19 15:48:00 <HapHiC_pipeline.py> [main] Pipeline started, HapHiC version: 1.0.3 (update: 2024.05.08)
2024-05-19 15:48:00 <HapHiC_pipeline.py> [main] Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
2024-05-19 15:48:00 <HapHiC_pipeline.py> [haphic_cluster] Step1: Execute preprocessing and Markov clustering for contigs...
2024-05-19 15:48:01 <HapHiC_cluster.py> [run] Program started, HapHiC version: 1.0.3 (update: 2024.05.08)
2024-05-19 15:48:01 <HapHiC_cluster.py> [run] Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:45:18) [GCC 12.3.0]
2024-05-19 15:48:01 <HapHiC_cluster.py> [detect_format] The file for Hi-C read alignments is detected as being in BAM format
2024-05-19 15:48:01 <HapHiC_cluster.py> [run] Ultra-long data are not supported now when assembly correction is enabled
2024-05-19 15:48:01 <HapHiC_cluster.py> [parse_fasta] Parsing input FASTA file...
2024-05-19 15:48:13 <HapHiC_cluster.py> [parse_bam_for_correction] Parsing input BAM file for contig correction...
2024-05-19 16:07:10 <HapHiC_cluster.py> [correct_assembly] Performing assembly correction...
2024-05-19 16:41:32 <HapHiC_cluster.py> [correct_assembly] Correction round 1, breakpoints are detected in 11 contig(s)
2024-05-19 16:41:32 <HapHiC_cluster.py> [break_and_update_ctgs] Breaking contigs and updating data...
2024-05-19 16:41:32 <HapHiC_cluster.py> [correct_assembly] Correction round 2, breakpoints are detected in 7 contig(s)
2024-05-19 16:41:32 <HapHiC_cluster.py> [break_and_update_ctgs] Breaking contigs and updating data...
2024-05-19 16:41:32 <HapHiC_cluster.py> [correct_assembly] Generating corrected assembly file...
2024-05-19 16:41:32 <HapHiC_cluster.py> [correct_assembly] 11 contigs were broken into 29 contigs. Writing corrected assembly to corrected_asm.fa...
2024-05-19 16:41:43 <HapHiC_cluster.py> [stat_fragments] Making some statistics of fragments (contigs / bins)
2024-05-19 16:41:43 <HapHiC_cluster.py> [stat_fragments] bin_size is calculated to be 742887 bp
2024-05-19 16:41:52 <HapHiC_cluster.py> [parse_alignments] Parsing input alignments...
2024-05-19 16:53:43 <HapHiC_cluster.py> [output_pickle] Writing HT_link_dict to HT_links.pkl...
2024-05-19 16:53:43 <HapHiC_cluster.py> [output_clm] Writing clm_dict to paired_links.clm...
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] Filtering fragments...
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [Nx filtering] 2953 fragments kept
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [RE sites filtering] 0 fragments removed, 2953 fragments kept
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [link density filtering] Parameter --density_lower 0.2X is set to "multiple" mode and equivalent to 0.9979681679647816 in "fraction" mode
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [link density filtering] Parameter --density_upper 1.9X is set to "multiple" mode and equivalent to 1.0 in "fraction" mode
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [link density filtering] 2947 fragments removed, 6 fragments kept
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] Q1=26.0, median=26.0, Q3=26.0, IQR=Q3-Q1=0.0
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] Parameter --rank_sum_upper 1.5X is set to "multiple" mode and equivalent to 1.0 in "fraction" mode
2024-05-19 16:53:43 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] 0 fragments removed, 6 fragments kept
2024-05-19 16:53:43 <HapHiC_cluster.py> [remove_allelic_HiC_links] Removing Hi-C links between alleic contig pairs...
2024-05-19 16:53:43 <HapHiC_cluster.py> [remove_allelic_HiC_links] Removing isolated fragments after filtering out allelic Hi-C links...
2024-05-19 16:53:43 <HapHiC_cluster.py> [remove_allelic_HiC_links] 0 fragments removed, 6 fragments kept
2024-05-19 16:53:43 <HapHiC_cluster.py> [output_pickle] Writing full_link_dict to full_links.pkl...
2024-05-19 16:53:43 <HapHiC_cluster.py> [run] Hi-C linking matrix was constructed in 3942.0703554153442s
2024-05-19 16:53:43 <HapHiC_cluster.py> [run_mcl_clustering] Performing Markov clustering...
2024-05-19 16:53:43 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.1, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:43 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.2, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:43 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.3, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:44 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.4, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:45 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.5, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:45 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.6, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:46 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.7, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:46 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.8, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:46 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 1.9, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:47 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.0, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:47 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.1, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:48 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.2, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:49 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.3, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:49 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.4, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:49 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.5, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:50 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.6, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:50 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.7, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:51 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.8, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:51 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 2.9, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:52 <HapHiC_cluster.py> [mcl] The matrix has converged after 3 rounds of iterations (expansion: 2, inflation: 3.0, maximum iterations: 200, pruning threshold: 0.0001)
2024-05-19 16:53:52 <HapHiC_cluster.py> [run_mcl_clustering] The maximum number of clusters (3) is even less than the expected number of chromosomes (123). You could try higher inflation.
2024-05-19 16:53:52 <HapHiC_cluster.py> [run] 20 round(s) of Markov clustering finished in 9.17163634300232s, average 0.458581817150116s per round
2024-05-19 16:53:52 <HapHiC_cluster.py> [output_statistics] Making some statistics for the next HapHiC reassignment step...
2024-05-19 16:54:11 <HapHiC_cluster.py> [run] Program finished in 3970.5241661071777s
Traceback (most recent call last):
  File "/home/sofware/HapHiC-main/scripts/HapHiC_pipeline.py", line 517, in <module>
    main()
  File "/home/sofware/HapHiC-main/scripts/HapHiC_pipeline.py", line 498, in main
    haphic_cluster(args)
  File "/home/sofware/HapHiC-main/scripts/HapHiC_pipeline.py", line 390, in haphic_cluster
    raise RuntimeError(
RuntimeError: Pipeline Abortion: Inflation recommendation failed. It seems that some chromosomes were grouped together, or the maximum number of clusters is even less than the expected number of chromosomes. For 
more details, please check out the logs.
Traceback (most recent call last):
  File "/home/sofware/HapHiC-main/haphic", line 110, in <module>
    subprocess.run(commands, check=True)
  File "/home/micromamba/envs/haphic/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/sofware/HapHiC-main/scripts/HapHiC_pipeline.py', 'asm_ctgs_m.fa', 'HiC.filtered.bam', '123', '--correct_nrounds', '2', '--remove_allelic_
links', '3', '--threads', '40', '--processes', '40']' returned non-zero exit status 1.

```

**Comment by zengxiaofei** [comment]
I notice that the rank-sum values of contigs are quite low and the matrix converged after only 3 rounds of iterations. Could you please show me how these Hi-C reads were mapped and filtered? Some users reported similar issues, and we finally found that they used the same FASTQ file for paired reads.

**Comment by ZJin2021** [comment]
Thank you for the reminder. Oh, I found some wrongs with the alignment. I will run haphic again after making the modifications.
