### ISSUE TITLE
scikit-learn error, ImportError: dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by Boer223** [zengxiaofei/HapHiC#4]
Hi,
When I run the haphic pipeline, it occurs the following error:
```
(haphic) [cuixb@yls allhic]$ ~/tools/biosoft/HapHiC-main/haphic pipeline -h
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/site-packages/sklearn/__check_build/__init__.py", line 48, in <module>
    from ._check_build import check_build  # noqa
ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py", line 17, in <module>
    import HapHiC_cluster
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_cluster.py", line 31, in <module>
    from sklearn.preprocessing import normalize
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/site-packages/sklearn/__init__.py", line 81, in <module>
    from . import __check_build  # noqa: F401
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/site-packages/sklearn/__check_build/__init__.py", line 50, in <module>
    raise_build_error(e)
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/site-packages/sklearn/__check_build/__init__.py", line 31, in raise_build_error
    raise ImportError(
ImportError: dlopen: cannot load any more object with static TLS
___________________________________________________________________________
Contents of /home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/site-packages/sklearn/__check_build:
_check_build.cpython-310-x86_64-linux-gnu.so__init__.py               setup.py
__pycache__
___________________________________________________________________________
It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget
to build the package before using it: run `python setup.py install` or
`make` in the source directory.

If you have used an installer, please check that it is suited for your
Python version, your operating system and your platform.
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/HapHiC-main/haphic", line 96, in <module>
    subprocess.run(commands, check=True)
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py', '-h']' returned non-zero exit status 1.
```
And I installed Haphic env as your recommended: `conda env create -f HapHiC/conda_env/environment_py310.yml`.

**Comment by zengxiaofei** [comment]
Hi Xiaobo,

I guess it may be caused by the version of `glibc` on your system. According to [this issue](https://github.com/scikit-learn/scikit-learn/issues/14485), the version of `glibc` should `>=2.21`. You can check the version using this command: `ldd --version`.

If you are not the superuser, you could try solving the environment of HapHiC through installing an older version of `scikit-learn`.

Best regards,
Xiaofei

**Comment by Boer223** [comment]
Thanks! I'll try it.

**Comment by Boer223** [comment]
@zengxiaofei 
After I downgraded the version of scikit-learn, it can run some steps but also occurs the following error:
```
2023-12-14 21:13:19 <HapHiC_pipeline.py> [main] Pipeline started, HapHiC version: 1.0.2 (update: 2023.12.10)
2023-12-14 21:13:19 <HapHiC_pipeline.py> [main] Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
2023-12-14 21:13:19 <HapHiC_pipeline.py> [haphic_cluster] Step1: Execute preprocessing and Markov clustering for contigs...
2023-12-14 21:13:19 <HapHiC_cluster.py> [run] Program started, HapHiC version: 1.0.2 (update: 2023.12.10)
2023-12-14 21:13:19 <HapHiC_cluster.py> [run] Python version: 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) [GCC 7.5.0]
2023-12-14 21:13:19 <HapHiC_cluster.py> [run] Module sparse_dot_mkl or Intel MKL is not correctly installed, HapHiC will be executed in dense matrix mode
2023-12-14 21:13:19 <HapHiC_cluster.py> [parse_fasta] Parsing input FASTA file...
2023-12-14 21:13:37 <HapHiC_cluster.py> [stat_fragments] Making some statistics of fragments (contigs / bins)
2023-12-14 21:13:37 <HapHiC_cluster.py> [stat_fragments] bin_size is calculated to be 1038307 bp
2023-12-14 21:13:41 <HapHiC_cluster.py> [parse_bam] Parsing input BAM file...
Traceback (most recent call last):
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py", line 483, in <module>
    main()
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py", line 464, in main
    inflation = haphic_cluster(args)
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py", line 323, in haphic_cluster
    HapHiC_cluster.run(args, log_file=LOG_FILE)
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_cluster.py", line 2301, in run
    alignments, fa_dict, args, bin_size, frag_len_dict, Nx_frag_set, split_ctg_set)
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_cluster.py", line 1450, in parse_bam
    for ref, mref, pos, mpos in alignments:
  File "/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_cluster.py", line 1355, in aln_generator
    with pysam.AlignmentFile(bam, mode='rb', threads=threads, format_options=format_options) as f:
  File "pysam/libcalignmentfile.pyx", line 741, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 949, in pysam.libcalignmentfile.AlignmentFile._open
  File "pysam/libchtslib.pyx", line 585, in pysam.libchtslib.HTSFile.add_hts_options
RuntimeError: Invalid format option (b'filter=flag.read1') specified
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/HapHiC-main/haphic", line 96, in <module>
    subprocess.run(commands, check=True)
  File "/home/cuixb/tools/biosoft/conda3/envs/haphic2/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/raid8/cuixb/tools/biosoft/HapHiC-main/scripts/HapHiC_pipeline.py', 'watershield_asm.p_ctg.fa', 'HiC.filtered.bam', '36']' returned non-zero exit status 1.
```

**Comment by zengxiaofei** [comment]
> RuntimeError: Invalid format option (b'filter=flag.read1') specified

This information suggests that the version of `pysam` is outdated and incompatible with the newly introduced API of `htslib`.

You need to upgrade `pysam`. Additionally, maybe your Python is also somewhat out-of-date.

Xiaofei

**Comment by Boer223** [comment]
OK. Thanks.
