### ISSUE TITLE
The command "haphic pipeline asm.fa HiC.filtered.bam 11" encountered an error: "<Signals.SIGSEGV: 11>". 

### ISSUE THREAD

**Issue by S-iff** [zengxiaofei/HapHiC#57]
I ran the command: `/share/org/HapHiC/haphic pipeline MM.p_ctg.fa MMHiC.filtered.bam 11` with the species karyotype of 2N=2X=22. The method used for genome assembly is "hifiasm + Hi-C". The N10-N90 values are as follows:
#### scaffold statistics ####
Nx      Number  Length
N10     1       70351424
N20     2       38104393
N30     3       36331428
N40     4       36272373
N50     5       35837822
N60     7       29728330
N70     8       22796425
N80     10      17587200
N90     167     70139
longest scaffold: 70351424, shortest scaffold: 19888
total number: 1154, total length: 426116389
However, I encountered the following error log:
```shell
Line 6: /share/org/pth/HapHiC/haphic check
Line 9: /share/org/pth/HapHiC/haphic pipeline MM.p_ctg.fa MMHiC.filtered.bam 11
2024-08-29 20:14:51 <HapHiC_pipeline.py> [main] Pipeline started, HapHiC version: 1.0.5 (update: 2024.08.08)
2024-08-29 20:14:51 <HapHiC_pipeline.py> [main] Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
2024-08-29 20:14:51 <HapHiC_pipeline.py> [main] Command: /share/org/pth/HapHiC/scripts/HapHiC_pipeline.py MM.p_ctg.fa MMHiC.filtered.bam 11
2024-08-29 20:14:51 <HapHiC_pipeline.py> [haphic_cluster] Step1: Execute preprocessing and Markov clustering for contigs...
2024-08-29 20:15:01 <HapHiC_cluster.py> [run] Program started, HapHiC version: 1.0.5 (update: 2024.08.08)
2024-08-29 20:15:01 <HapHiC_cluster.py> [run] Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
2024-08-29 20:15:01 <HapHiC_cluster.py> [run] Command: /share/org/pth/HapHiC/scripts/HapHiC_pipeline.py MM.p_ctg.fa MMHiC.filtered.bam 11
2024-08-29 20:15:01 <HapHiC_cluster.py> [detect_format] The file for Hi-C read alignments is detected as being in BAM format
2024-08-29 20:15:01 <HapHiC_cluster.py> [parse_fasta] Parsing input FASTA file...
2024-08-29 20:15:03 <HapHiC_cluster.py> [stat_fragments] Making some statistics of fragments (contigs / bins)
2024-08-29 20:15:03 <HapHiC_cluster.py> [stat_fragments] bin_size is calculated to be 1291261 bp
2024-08-29 20:15:04 <HapHiC_cluster.py> [parse_alignments] Parsing input alignments...
2024-08-29 20:17:47 <HapHiC_cluster.py> [output_pickle] Writing HT_link_dict to HT_links.pkl...
2024-08-29 20:17:47 <HapHiC_cluster.py> [output_clm] Writing clm_dict to paired_links.clm...
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] Filtering fragments...
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [Nx filtering] 265 fragments kept
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [RE sites filtering] 0 fragments removed, 265 fragments kept
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [link density filtering] Parameter --density_lower 0.2X is set to "multiple" mode and equivalent to 0.0 in "fraction" mode
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [link density filtering] Parameter --density_upper 1.9X is set to "multiple" mode and equivalent to 1.0 in "fraction" mode
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [link density filtering] 0 fragments removed, 265 fragments kept
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] Q1=246.0, median=280.0, Q3=346.0, IQR=Q3-Q1=100.0
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] Parameter --rank_sum_upper 1.5X is set to "multiple" mode and equivalent to 0.9056603773584906 in "fraction" mode
2024-08-29 20:18:16 <HapHiC_cluster.py> [filter_fragments] [rank sum filtering] 25 fragments removed, 240 fragments kept
2024-08-29 20:18:16 <HapHiC_cluster.py> [output_pickle] Writing full_link_dict to full_links.pkl...
2024-08-29 20:18:16 <HapHiC_cluster.py> [run] Hi-C linking matrix was constructed in 194.95615482330322s
2024-08-29 20:18:16 <HapHiC_cluster.py> [run_mcl_clustering] Performing Markov clustering...
2024-08-29 20:18:17 <HapHiC_cluster.py> [mcl] The matrix has converged after 66 rounds of iterations (expansion: 2, inflation: 1.1, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:20 <HapHiC_cluster.py> [mcl] The matrix has converged after 33 rounds of iterations (expansion: 2, inflation: 1.2, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:34 <HapHiC_cluster.py> [mcl] The matrix has converged after 22 rounds of iterations (expansion: 2, inflation: 1.3, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:38 <HapHiC_cluster.py> [mcl] The matrix has converged after 17 rounds of iterations (expansion: 2, inflation: 1.4, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:40 <HapHiC_cluster.py> [mcl] The matrix has converged after 23 rounds of iterations (expansion: 2, inflation: 1.5, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:40 <HapHiC_cluster.py> [mcl] The matrix has converged after 18 rounds of iterations (expansion: 2, inflation: 1.6, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:41 <HapHiC_cluster.py> [mcl] The matrix has converged after 16 rounds of iterations (expansion: 2, inflation: 1.7, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:41 <HapHiC_cluster.py> [mcl] The matrix has converged after 15 rounds of iterations (expansion: 2, inflation: 1.8, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:41 <HapHiC_cluster.py> [mcl] The matrix has converged after 15 rounds of iterations (expansion: 2, inflation: 1.9, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 18 rounds of iterations (expansion: 2, inflation: 2.0, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 19 rounds of iterations (expansion: 2, inflation: 2.1, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 22 rounds of iterations (expansion: 2, inflation: 2.2, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 15 rounds of iterations (expansion: 2, inflation: 2.3, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 12 rounds of iterations (expansion: 2, inflation: 2.4, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 13 rounds of iterations (expansion: 2, inflation: 2.5, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 11 rounds of iterations (expansion: 2, inflation: 2.6, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 10 rounds of iterations (expansion: 2, inflation: 2.7, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 11 rounds of iterations (expansion: 2, inflation: 2.8, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 13 rounds of iterations (expansion: 2, inflation: 2.9, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [mcl] The matrix has converged after 10 rounds of iterations (expansion: 2, inflation: 3.0, maximum iterations: 200, pruning threshold: 0.0001)
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] The length ratio (0.75) might be too strict, trying a lower one...
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] The length ratio (0.7) might be too strict, trying a lower one...
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] The length ratio (0.65) might be too strict, trying a lower one...
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] The length ratio (0.6) might be too strict, trying a lower one...
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] The length ratio (0.55) might be too strict, trying a lower one...
2024-08-29 20:18:42 <HapHiC_cluster.py> [recommend_inflation] You could try inflation from 2.0 (length ratio = 0.5)
2024-08-29 20:18:42 <HapHiC_cluster.py> [run] 20 round(s) of Markov clustering finished in 25.706380128860474s, average 1.2853190064430238s per round
2024-08-29 20:18:42 <HapHiC_cluster.py> [output_statistics] Making some statistics for the next HapHiC reassignment step...
2024-08-29 20:18:55 <HapHiC_cluster.py> [run] Program finished in 233.30833339691162s
2024-08-29 20:18:55 <HapHiC_pipeline.py> [haphic_reassign] Step2: Reassign and rescue contigs...
2024-08-29 20:19:07 <HapHiC_reassign.py> [run] Program started, HapHiC version: 1.0.5 (update: 2024.08.08)
2024-08-29 20:19:07 <HapHiC_reassign.py> [run] Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
2024-08-29 20:19:07 <HapHiC_reassign.py> [run] Command: /share/org/pth/HapHiC/scripts/HapHiC_pipeline.py MM.p_ctg.fa MMHiC.filtered.bam 11
2024-08-29 20:19:07 <HapHiC_cluster.py> [parse_fasta] Parsing input FASTA file...
2024-08-29 20:19:08 <HapHiC_reassign.py> [parse_pickle] Parsing input pickle file...
2024-08-29 20:19:08 <HapHiC_reassign.py> [parse_clusters] Parsing .clusters.txt file...
2024-08-29 20:19:08 <HapHiC_reassign.py> [run] File parsing and data preparation finished in 1.5187973976135254s
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] Performing reassignment...
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] [result::round1] Total: 1154, consistent: 5, rescued: 8, reassigned: 0, not rescued: 1141
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] Performing reassignment...
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] [result::round2] Total: 1154, consistent: 13, rescued: 0, reassigned: 0, not rescued: 1141
2024-08-29 20:19:08 <HapHiC_reassign.py> [run] [result::round2] Result has converged after 1 rounds of reassignment, break
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] Performing additional round of rescue...
2024-08-29 20:19:08 <HapHiC_reassign.py> [run_reassignment] [result::additional_rescue] Total: 1154, consistent: 21, rescued: 4, reassigned: 0, not rescued: 1129
2024-08-29 20:19:08 <HapHiC_reassign.py> [run] 2 round(s) of reassignment finished in 0.07977032661437988s, average 0.03988516330718994s per round
2024-08-29 20:19:08 <HapHiC_reassign.py> [run] Parameter --nclusters (11) is equal to the number of clusters (11) after reassignment, skip Agglomerative Hierarchical Clustering
2024-08-29 20:19:08 <HapHiC_reassign.py> [split_clm_file] Splitting clm file into subfiles by group...
2024-08-29 20:19:16 <HapHiC_reassign.py> [run] Program finished in 9.750131845474243s
2024-08-29 20:19:16 <HapHiC_pipeline.py> [haphic_sort] Step3: Order and orient contigs within each group...
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Program started, HapHiC version: 1.0.5 (update: 2024.08.08)
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Python version: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Command: /share/org/pth/HapHiC/scripts/HapHiC_sort.py /share/org/pth/HiFi/MM.p_ctg.fa /share/org/pth/HiFi/01.cluster/HT_links.pkl /share/org/pth/HiFi/02.reassign/split_clms /share/org/pth/HiFi/02.reassign/final_groups/group5_35837822bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group1_70654378bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group6_32394756bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group8_27911542bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group4_36272373bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group2_38133982bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group9_27568272bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group11_14714105bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group3_37032754bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group7_29728330bp.txt /share/org/pth/HiFi/02.reassign/final_groups/group10_17846258bp.txt --flanking_region 0 --density_cal_method multiplication --confidence_cutoff 1 --mutprob 0.2 --ngen 5000 --npop 100 --seed 42 --processes 8
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Checking the path of ALLHiC...
2024-08-29 20:19:17 <HapHiC_sort.py> [run] ALLHiC has been found in /share/org/pth/HapHiC/scripts
2024-08-29 20:19:17 <HapHiC_sort.py> [parse_fasta] Parsing fasta file...
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Loading input pickle file...
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Parsing group files and clm files...
2024-08-29 20:19:17 <HapHiC_sort.py> [run] Program will be executed in multiprocessing mode (processes=8)
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group5_35837822bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group5_35837822bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group5_35837822bp] Only 1 contig in the group file, neither ordering nor orientation is required
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group1_70654378bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group1_70654378bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group1_70654378bp] Starting fast sorting iterations...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group6_32394756bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group6_32394756bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group6_32394756bp] Only 1 contig in the group file, neither ordering nor orientation is required
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group8_27911542bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group8_27911542bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group8_27911542bp] Starting fast sorting iterations...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group4_36272373bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group4_36272373bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group2_38133982bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group4_36272373bp] Only 1 contig in the group file, neither ordering nor orientation is required
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group2_38133982bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group9_27568272bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group2_38133982bp] Starting fast sorting iterations...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group11_14714105bp] Performing fast sorting...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group9_27568272bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group11_14714105bp] Checking the content of input group file...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group9_27568272bp] Starting fast sorting iterations...
2024-08-29 20:19:17 <HapHiC_sort.py> [fast_sort] [group11_14714105bp] Starting fast sorting iterations...
2024-08-29 20:19:17 <HapHiC_sort.py> [run_allhic_optimization] [group1_70654378bp] Performing ALLHiC optimization...
2024-08-29 20:19:17 <HapHiC_sort.py> [run_allhic_optimization] [group2_38133982bp] Performing ALLHiC optimization...
2024-08-29 20:19:17 <HapHiC_sort.py> [run_allhic_optimization] [group11_14714105bp] Performing ALLHiC optimization...
2024-08-29 20:19:17 <HapHiC_sort.py> [run_allhic_optimization] [group8_27911542bp] Performing ALLHiC optimization...
2024-08-29 20:19:17 <HapHiC_sort.py> [run_allhic_optimization] [group9_27568272bp] Performing ALLHiC optimization...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group3_37032754bp] Performing fast sorting...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group7_29728330bp] Performing fast sorting...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group3_37032754bp] Checking the content of input group file...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group10_17846258bp] Performing fast sorting...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group7_29728330bp] Checking the content of input group file...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group3_37032754bp] Starting fast sorting iterations...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group10_17846258bp] Checking the content of input group file...
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group7_29728330bp] Only 1 contig in the group file, neither ordering nor orientation is required
2024-08-29 20:19:18 <HapHiC_sort.py> [fast_sort] [group10_17846258bp] Starting fast sorting iterations...
2024-08-29 20:19:18 <HapHiC_sort.py> [run_allhic_optimization] [group3_37032754bp] Performing ALLHiC optimization...
2024-08-29 20:19:18 <HapHiC_sort.py> [run_allhic_optimization] [group10_17846258bp] Performing ALLHiC optimization...
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group1_70654378bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group1_70654378bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group8_27911542bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group8_27911542bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group2_38133982bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group2_38133982bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group9_27568272bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group9_27568272bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group11_14714105bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group11_14714105bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group3_37032754bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group3_37032754bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
2024-08-29 20:19:24 <HapHiC_sort.py> [check_exceptions] Command '['/share/org/pth/HapHiC/scripts/allhic', 'optimize', '/share/org/pth/HiFi/02.reassign/final_groups/group10_17846258bp.txt', '/share/org/pth/HiFi/02.reassign/split_clms/group10_17846258bp.clm', '--mutapb', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--resume']' died with <Signals.SIGSEGV: 11>.
Traceback (most recent call last):
  File "/share/org/pth/HapHiC/scripts/HapHiC_sort.py", line 971, in <module>
    main()
  File "/share/org/pth/HapHiC/scripts/HapHiC_sort.py", line 967, in main
    run(args, log_file='HapHiC_sort.log')
  File "/share/org/pth/HapHiC/scripts/HapHiC_sort.py", line 949, in run
    check_exceptions(result_list)
  File "/share/org/pth/HapHiC/scripts/HapHiC_sort.py", line 768, in check_exceptions
    raise Exception('{} exception(s) detected, please check the log above.'.format(nerrors))
Exception: 7 exception(s) detected, please check the log above.
Traceback (most recent call last):
  File "/share/org/pth/HapHiC/scripts/HapHiC_pipeline.py", line 529, in <module>
    main()
  File "/share/org/pth/HapHiC/scripts/HapHiC_pipeline.py", line 518, in main
    haphic_sort(args)
  File "/share/org/pth/HapHiC/scripts/HapHiC_pipeline.py", line 452, in haphic_sort
    subprocess.run(commands, check=True)
  File "/share/org/pth/.conda/envs/haphic/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/share/org/pth/HapHiC/scripts/HapHiC_sort.py', '/share/org/pth/HiFi/MM.p_ctg.fa', '/share/org/pth/HiFi/01.cluster/HT_links.pkl', '/share/org/pth/HiFi/02.reassign/split_clms', '/share/org/pth/HiFi/02.reassign/final_groups/group5_35837822bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group1_70654378bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group6_32394756bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group8_27911542bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group4_36272373bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group2_38133982bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group9_27568272bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group11_14714105bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group3_37032754bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group7_29728330bp.txt', '/share/org/pth/HiFi/02.reassign/final_groups/group10_17846258bp.txt', '--flanking_region', '0', '--density_cal_method', 'multiplication', '--confidence_cutoff', '1', '--mutprob', '0.2', '--ngen', '5000', '--npop', '100', '--seed', '42', '--processes', '8']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/share/org/pth/HapHiC/haphic", line 117, in <module>
    subprocess.run(commands, check=True)
  File "/share/org/pth/.conda/envs/haphic/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/share/org/pth/HapHiC/scripts/HapHiC_pipeline.py', 'MM.p_ctg.fa', 'MMHiC.filtered.bam', '11']' returned non-zero exit status 1.
Job 536114 stderr output:
``` 

Could you please help me identify what went wrong? Your assistance would be greatly appreciated.

Best regards,

iff

**Comment by zengxiaofei** [comment]
I have not seen this error message before. But it could be a problem of ALLHiC optimization. You can skip the optimization process using the parameter `--skip_allhic`. I noticed that your contigs are very long (chromosome-level or near chromosome-level), and the clustering process may have some problems. You may also consider using the [quick view mode](https://github.com/zengxiaofei/HapHiC#quick-view-mode) instead. This approach can skip both the clustering step and the ALLHiC optimization process.

**Comment by S-iff** [comment]
感谢您的建议，我在添加--quick_view参数后顺利运行完成了这一步。但我在运行下一步 Juicebox curation， bash juicebox.sh时的命令时，/path/to/HapHiC/utils/juicer/scripts/../utils/juicer pre -a -q 1 -o out_JBAT /share/org/HiFi/MMHiC.filtered.bam scaffolds.raw.agp MM.p_ctg.fa.fai >out_JBAT.log 2>&1报Segmentation fault (core dumped)的错误，询问服务器运维人员得知该代码可能自行引用了内存，但我所用集群是禁止程序自行使用内存的，不知这个情况能否解决。
/
Line 9: ln -s /share/org/HiFi/MM.p_ctg.fa .
ln: failed to create symbolic link './MM.p_ctg.fa': File exists
Line 10: samtools faidx MM.p_ctg.fa
Line 11: /share/org/HapHiC/scripts/../utils/juicer pre -a -q 1 -o out_JBAT /share/org/HiFi/MMHiC.filtered.bam scaffolds.raw.agp MM.p_ctg.fa.fai
/share/org/HiFi/MM04.build/juicebox.sh: line 11: 2377950 **Segmentation fault      (core dumped)**

**Comment by zengxiaofei** [comment]
I am unsure of the limitations that your system administrators have set. However, it appears that all binary programs pre-compiled by me, including allhic and juicer, did not execute properly. I am uncertain if compiling these two programs yourself could resolve this issue. You can access the source code for these programs here: allhic (Golang) at https://github.com/zengxiaofei/allhic and yahs (C language) at https://github.com/zengxiaofei/yahs.

**Comment by zengxiaofei** [comment]
Close this issue as there has been no response for two weeks.
