### ISSUE TITLE
Sort and locate the HIC heatmap using the reference genome

### ISSUE THREAD

**Issue by cht-jk** [zengxiaofei/HapHiC#69]
Hello, Zeng：
Sort and locate the HIC heatmap using the reference genome:
（1）minimap2 -x asm20 -N 1 -t 30 sanqi_delete_scaffold.fa zzs.p_ctg.fasta -o asm_to_ref.paf
（2）haphic refsort ../scaffolds.raw.agp asm_to_ref.paf > scaffolds.refsort.agp
（3）haphic plot scaffolds.refsort.agp ../../HiC.filtered.bam --bin_size 1000 --min_len 5 --threads 20
Among them, zzs.t_ctg.fasta is tetraploid, and the resulting heatmap did not show the clustering of the four chromosomes as shown in the example (sugarcane).
thanks!
[contact_map.pdf](https://github.com/user-attachments/files/17127301/contact_map.pdf)

**Comment by zengxiaofei** [comment]
The reference genome you selected might be phylogenetically too distant from the species, leading to poor alignments when using minimap2. Consider using a reference genome from a closer species or try wfmash.

Is the species an autotetraploid or an allotetraploid? Based on the contact map and the name of the FASTA file, it appears that the genome assembly might not have been correctly assembled, or you may have used the wrong version. If the species is an autotetraploid, you may need to use the `p_utg` or `hap[1-4].p_ctg` instead of `p_ctg`.

More information:
* https://hifiasm.readthedocs.io/en/latest/interpreting-output.html#interpreting-output
* http://lh3.github.io/2021/04/17/concepts-in-phased-assemblies
* http://www.liheng.org/images/asmconcepts/phased-asm-flow.png

**Comment by cht-jk** [comment]
Hello, Zeng：
When I use wfmash for comparison:
wfmash ref.fa asm.fasta -m -n 1 -S 1 -t 40 | cut -f 1-6,8- > asm_to_ref_wfmash.paf
You will get the file asm_to-uref_wfmash.paf, and then run:
haphic refsort ../scaffolds.raw.agp asm_to_ref_wfmash.paf > scaffolds.refsort.agp， The following issues may occur:
2024-09-29 09:20:59 <HapHiC_refsort.py> [run] Program started, HapHiC version: 1.0.5 (update: 2024.07.22)
2024-09-29 09:20:59 <HapHiC_refsort.py> [run] Python version: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0]
2024-09-29 09:20:59 <HapHiC_refsort.py> [run] Command: /home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py ../ scaffolds.raw.agp asm_to_ref_wfmash.paf
2024-09-29 09:20:59 <HapHiC_refsort.py> [parse_agp] Parsing input AGP file...
2024-09-29 09:20:59 <HapHiC_refsort.py> [parse_paf] Parsing input PAF file...
Traceback (most recent call last):
File "/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py",  line 301, in <module>
main()
File "/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py", line 297, in main
run(args,  log_file='HapHiC_refsort.log')
File "/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py", line 288, in run
group_ref_dict = parse_paf(args.paf, ctg_group_dict)
File "/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py",  line 90, in parse_paf
if int(cols[11]) < 1:
ValueError: invalid literal for int() with base 10: 'id:f:0.941972'
Traceback (most recent call last):
File "/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/haphic",  line 117, in <module>
subprocess.run(commands, check=True)
File "/home/export/online3/caohaitao/conda3/lib/python3.9/subprocess.py", line 528, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/export/online3/caohaitao/HapHiC/haphic/HapHiC/scripts/HapHiC_refsort.py', '../ scaffolds.raw.agp', 'asm_to_ref_wfmash.paf']' returned non-zero exit status 1.
